### ISSUE TITLE
Okta.Sdk.Internal 403 error.  Cannot connect to Okta

### ISSUE THREAD

**Issue by kmccauley** [lithnet/okta-managementagent#6]
receiving an error:  (I am using the same account created in the Okta side as the account running the MIM Synchronization/OktaLithnet Connector.

 "System.AggregateException: One or more errors occurred. ---> Okta.Sdk.OktaApiException: 403: You do not have permission to perform the requested action

   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
   at Okta.Sdk.Internal.DefaultDataStore.<GetAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.OktaClient.<GetAsync>d__18`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Lithnet.Okta.ManagementAgent.SchemaProvider.<GetSchemaJson>d__4.MoveNext() in D:\github\lithnet\okta-managementagent\src\Lithnet.Okta.ManagementAgent\Providers\SchemaProvider.cs:line 105
   at Lithnet.Okta.ManagementAgent.SchemaProvider.GetSchemaTypeUser(IOktaClient client) in D:\github\lithnet\okta-managementagent\src\Lithnet.Okta.ManagementAgent\Providers\SchemaProvider.cs:line 95
   at Lithnet.Okta.ManagementAgent.SchemaProvider.GetMmsSchema(SchemaContext context) in D:\github\lithnet\okta-managementagent\src\Lithnet.Okta.ManagementAgent\Providers\SchemaProvider.cs:line 20
   at Lithnet.Ecma2Framework.Ecma2.GetSchema(KeyedCollection`2 configParameters) in D:\github\lithnet\okta-managementagent\src\Lithnet.Okta.ManagementAgent\obj\Debug\ILTemplate.cs:line 0
---> (Inner Exception #0) Okta.Sdk.OktaApiException: 403: You do not have permission to perform the requested action

   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
   at Okta.Sdk.Internal.DefaultDataStore.<GetAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.OktaClient.<GetAsync>d__18`1.MoveNext()<---
Forefront Identity Manager 4.4.1302.0"
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="FIMSynchronizationService" />
    <EventID Qualifiers="49152">6801</EventID>
    <Level>2</Level>
    <Task>3</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-04-22T17:08:52.379974700Z" />
    <EventRecordID>330119</EventRecordID>
    <Channel>Application</Channel>
    <Computer>usmtnpmdinfap17.emrsn.org</Computer>
    <Security />
  </System>
  <EventData>
    <Data>System.AggregateException: One or more errors occurred. ---&gt; Okta.Sdk.OktaApiException: 403: You do not have permission to perform the requested action

   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
   at Okta.Sdk.Internal.DefaultDataStore.&lt;GetAsync&gt;d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.OktaClient.&lt;GetAsync&gt;d__18`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Lithnet.Okta.ManagementAgent.SchemaProvider.&lt;GetSchemaJson&gt;d__4.MoveNext() in D:\github\lithnet\okta-managementagent\src\Lithnet.Okta.ManagementAgent\Providers\SchemaProvider.cs:line 105
   at Lithnet.Okta.ManagementAgent.SchemaProvider.GetSchemaTypeUser(IOktaClient client) in D:\github\lithnet\okta-managementagent\src\Lithnet.Okta.ManagementAgent\Providers\SchemaProvider.cs:line 95
   at Lithnet.Okta.ManagementAgent.SchemaProvider.GetMmsSchema(SchemaContext context) in D:\github\lithnet\okta-managementagent\src\Lithnet.Okta.ManagementAgent\Providers\SchemaProvider.cs:line 20
   at Lithnet.Ecma2Framework.Ecma2.GetSchema(KeyedCollection`2 configParameters) in D:\github\lithnet\okta-managementagent\src\Lithnet.Okta.ManagementAgent\obj\Debug\ILTemplate.cs:line 0
---&gt; (Inner Exception #0) Okta.Sdk.OktaApiException: 403: You do not have permission to perform the requested action

   at Okta.Sdk.Internal.DefaultDataStore.EnsureResponseSuccess(HttpResponse`1 response)
   at Okta.Sdk.Internal.DefaultDataStore.&lt;GetAsync&gt;d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Okta.Sdk.OktaClient.&lt;GetAsync&gt;d__18`1.MoveNext()&lt;---
Forefront Identity Manager 4.4.1302.0</Data>
  </EventData>
</Event>

**Comment by ryannewington** [comment]
As discussed offline, org-admin level rights are needed in the Okta tenant.
